# Generated by Django 3.1.4 on 2021-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
