# Generated by Django 3.1.4 on 2021-03-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0003_auto_20210313_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_number', models.IntegerField()),
                ('order_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_accepted', models.BooleanField(default=False, null=True)),
                ('customer_phone_number', models.CharField(max_length=12, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('field_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StadiumTimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadium.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('custumer', 'customer')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='stadiumtimeframe',
            name='time_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.timeframe'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='stadium_time_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.stadiumtimeframe'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.user'),
        ),
    ]
